name: Kotlin CI

on:
  push:
    paths:
      - '**.gradle'
      - '**.properties'
      - '**/src/**'
      - '.github/workflows/**'
    branches:
      - 'master'
    tags-ignore:
      - '*.*'
  pull_request:
    paths:
      - '**.gradle'
      - '**.properties'
      - '**/src/**'
    types: [ opened, synchronize, reopened ]

jobs:
  build_and_release:
    strategy:
      matrix:
        java: [ 16 ]
    name: Build and publish artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Push container to Docker Hub
        run: ./gradlew clean build test jib -Djib.to.auth.username=${{ secrets.DOCKER_USERNAME }} -Djib.to.auth.password=${{ secrets.DOCKER_PASSWORD }}
