server:
  port: 8282
  forward-headers-strategy: native

spring:
  webflux.base-path: "/api"

  r2dbc:
    username: ${POSTGRES_USERNAME}
    name: ${POSTGRES_DATABASE}
    password: ${POSTGRES_PASSWORD}
    url: "r2dbc:postgres://${POSTGRES_HOST}"

logging:
  level:
    root: INFO
    # io.r2dbc.postgresql: DEBUG # for the driver
    # io.r2dbc.postgresql.QUERY: DEBUG # for queries
    # io.r2dbc.postgresql.PARAM: DEBUG # for parameters
    # io.r2dbc.postgresql.client: DEBUG # for the client
